### PR TITLE
Add NTv2 grids for Portugal, for convertion between Portuguese Lisbon Datum and Datum 73 to ETRS89

### PR DESCRIPTION
**Pull request by PedroVenancio**

### CODE REVIEW

**Comment by PedroVenancio** [comment]
Hi @rouault 

Can you please review my PR, with portuguese NTv2 grids?

These grids are already referenced in EPSG dataset: 
https://github.com/OSGeo/proj.4/blob/master/data/sql/grid_transformation.sql#L193
https://github.com/OSGeo/PROJ/blob/master/data/sql/grid_transformation.sql#L194

Even so, it's necessary to update the grid_alternatives file?
https://github.com/OSGeo/PROJ/blob/master/data/sql/grid_alternatives.sql

Thank you very much!

**Comment by PedroVenancio** [comment]
I did the update to grid_alternatives.sql file

https://github.com/OSGeo/PROJ/pull/1571

**Comment by rouault** [comment]
Note to other maintainers: wait for resolution of https://github.com/OSGeo/PROJ/pull/1571#issuecomment-526852028 before merging this

**Comment by PedroVenancio** [comment]
> 
> 
> Note to other maintainers: wait for resolution of [OSGeo/PROJ#1571 (comment)](https://github.com/OSGeo/PROJ/pull/1571#issuecomment-526852028) before merging this

I think it is ready now @rouault .

Thank you very much!

**Comment by PedroVenancio** [comment]
Hi @kbevers @rouault 

Do you have any idea about when proj-datumgrid-europe 1.5 will be released? 

imagem

Thank you very much!

Best regards,
Pedro

**Comment by kbevers** [comment]
It will be released alongside PROJ 6.3.0 January 1st (or thereabouts)

**Comment by PedroVenancio** [comment]
Great!

Thanks @kbevers !

**Pull request merged**
