### PR TITLE
Add RH2000 .gtx grid for Sweden

### PR DESCRIPTION
**Pull request by ghost**
The .gtx file have been converted from the original *.txt
file distributed by the Lantmäteriet, the Swedish survey
agency:

https://www.lantmateriet.se/contentassets/493a548ae6c14631968c401dc08086c5/swen17_rh2000_txt.zip

The conversion is done by the europe/gri2gtx.py script.

### CODE REVIEW

**Comment by kbevers** [comment]
Thanks for adding this. 

You haven't include the `europe/gri2gtx.py` script and you need to append `SWEN17_RH2000.gtx` to `travis/expected_europe.lst` for the tests to pass. Otherwise this looks good.

It would be nice if you could put the conversion script in `scripts/`instead of `europe/` and give it a name that makes it clear what it is used for.

**Comment by ghost** [comment]
I have added `SWEN17_RH2000.gtx` to `travis/expected_europe.lst`, the test now passes \o/

The `europe/gri2gtx.py` script is already in the repository, it was part of my previous PR https://github.com/OSGeo/proj-datumgrid/pull/24.

Do you want me to move it `scripts/` in this PR?

About the script's name, not sure what else I should call it. It is a script for converting data from GRI to GTX format, any suggestions?

**Comment by kbevers** [comment]
> The `europe/gri2gtx.py` script is already in the repository, it was part of my previous PR #24.

Ah, sorry I missed that. 

> Do you want me to move it `scripts/` in this PR?

That would be nice, yes. No need to rename it - I thought it was a one-off script, in which case I think it would make sense to have the name describe what it does. But that is already the case so please keep the name :-)

**Comment by sebastic** [comment]
Note that there are already several scripts outside the `scripts` directory:
```
./build_egm96_15_gtx.sh
./europe/build_french_vgrids.sh
./europe/gri2gtx.py
./north-america/build_g2012.sh
./north-america/build_nad83_harn.sh
./north-america/vertcon_94_to_gtx.py
./world/build_egm08_25_gtx.sh
```

The status quo is to have the script in the same directory as the grid files it produces.

I agree that it would be good to standardize on using the `scripts` directory for those scripts, but that is outside the scope of this PR.

**Comment by kbevers** [comment]
> but that is outside the scope of this PR.

Good point, @sebastic. I'll merge this as is. The scripts can be moved around later.

**Comment by ghost** [comment]
Cool, thanks for merging!

**Comment by rouault** [comment]
Should there be an entry added in the proj.db so that this grid is proposed when asking for SWEREF99 to RH2000 ?

**Comment by rouault** [comment]
Note: https://github.com/OSGeo/proj.4/pull/1280 adds a custom entry in proj.db for this grid

**Pull request merged**
