### PR TITLE
Add OSTN15 transformation grid for datum shifts

### LINKED ISSUE #21: Include OSTN02_NTv2.gsb and OSTN15 (Great Britain)
Hello,
While looking at https://github.com/OSGeo/proj.4/issues/904 I noticed the ESRI file uses 102 times the NTv2 grid "OSTN02_NTv2.gsb".
I found it [here](https://www.ordnancesurvey.co.uk/business-and-government/help-and-support/navigation-technology/os-net/ostn02-ntv2-format.html).
The license seems OK:
```
The OSTN02 data in NTv2 format is licensed to users pursuant to the terms of the Open Source Initiative BSD Licence (see the opensource bsd license page).

The copyright notice which must be attached to the software under the terms of the BSD licence is as follows:

'© Crown copyright, Ordnance Survey and the Ministry of Defence (MOD) 2002. All rights reserved.
```
Should it be included in this package?

### PR DESCRIPTION
**Pull request by wonder-sk**
See https://www.ordnancesurvey.co.uk/business-and-government/help-and-support/navigation-technology/os-net/formats-for-developers.html

Fixes #21

### CODE REVIEW

**Comment by rouault** [comment]
I was a bit surprised on the direction ETRStoOSGB claimed in the name, but while double checking with the Helmert transformation from EPSG to go from OSGB36 to ETRS89, I see that the hgridshift operation on OSTN15_NTv2_ETRStoOSGB.gsb has to be inversed, so things are consistent.

However looking at https://www.ordnancesurvey.co.uk/docs/gps/OSTN15_NTv2.zip, I see it contains also OSTN15_NTv2_OSGBtoETRS.gsb, and that one is the one referenced by EPSG (https://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:coordinateOperation:EPSG::7709), so I'm wondering if it wouldn't be better to include rather this one (which would be more in the tradition too of grid files in PROJ that go from "old system" to WGS84 (or system ~= WGS84 such as ETRS89)

```
$ echo "50 0 0" | src/cct -d 8 +proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +inv +proj=longlat +a=6377563.396 +rf=299.3249646 +step +proj=cart +a=6377563.396 +rf=299.3249646 +step +proj=helmert +x=446.448 +y=-125.157 +z=542.06 +rx=0.15 +ry=0.247 +rz=0.842 +s=-20.489 +convention=position_vector +step +inv +proj=cart +ellps=GRS80 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
  50.00068590    -0.00156114   43.99795223           inf

$ echo "50 0 0" | src/cct -d 8 +proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=hgridshift +inv +grids=./OSTN15_NTv2_ETRStoOSGB.gsb +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
  50.00068270    -0.00153270    0.00000000           inf

$ echo "50 0 0" | src/cct -d 8 +proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=hgridshift +grids=./OSTN15_NTv2_OSGBtoETRS.gsb +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
  50.00068269    -0.00153271    0.00000000           inf
```
(the very slight difference, of the order of 1e-8 deg / 1mm, between the use of the 2 grids is due to the fact that while using the ETRStoOSGB in the reverse direction, PROJ applies an iterative refinement from a guessed solution)

**Comment by wonder-sk** [comment]
Okay I have updated the PR to use the other direction (OSGBtoETRS) - I guess it is better to use the file as recorded in EPSG database, so thanks for pointing it out. I have originally opted for ETRStoOSGB because apparently that's the grid file that was released originally by OS and the other direction was added later (according to 'CREATED' timestamp in the .gsb files) so I thought the former is the canonical data file.

**Comment by rouault** [comment]
Could you squash the commits in a single one ?

**Comment by wonder-sk** [comment]
Squashed now

**Comment by rouault** [comment]
@kbevers Good for you ?

**Comment by kbevers** [comment]
Yes, Thank you @wonder-sk!

**Comment by rouault** [comment]
@wonder-sk  I've noticed very recently that producers of geodetic shift grids have interpreted differently the NTv2 specification regarding on the units for the channels that give accuracy
values. My findings is that some agencies have interpreted them as being values expressed in arc-seconds and others as metres...
The summary is there:
https://github.com/OSGeo/PROJ/wiki/Units-of-NTv2-accuracy-samples-%3F
Could you try to connect with Ordnance Survey to check which interpretation (second vs metre) they have selected ?

**Comment by wonder-sk** [comment]
I have sent an inquiry about that - let's see if/when they come back to me...

**Pull request merged**
