### PR TITLE
Europe: add French vertical grids to convert from national vertical datum to ellipsoid height

### PR DESCRIPTION
**Pull request by rouault**
A few of them are referenced by the EPSG dataset, and most
others by the IGNF registry.

### CODE REVIEW

**Comment by kbevers** [comment]
I know it is very unlikely, but is the grid license available in English?

**Comment by rouault** [comment]
Note: similarly to what is done with US, I've put the data for all the overseas French territory in the Europe package. Otherwise would have to be split among North-America, Oceania, and a to-be-created Antartica (for Kerguelen islands...)

**Comment by rouault** [comment]
> I know it is very unlikely, but is the grid license available in English?

Couldn't find one. The license text explicitly mentions end of page 2 that the license if designed to be compatible with all free licenses that require at least attribution mentions, and in particular with «Creative  Commons  Attribution»(CC-BY)  of  Creative  Commons and «Open Data Commons attribution»(ODC-BY) of Open Knowledge Foundation. So for practical purposes it can be used as CC-BY data. And the rough translation of the first paragraph is:
```
The user is free of reusing "information" (that is data):
- copying and reproducing it
- adapt, modify, extract, transform to create derived products and services
- to communicate, share, publish, transmit it
- to use it for commercial, for example, by combining it with other information or integrating it into its own product
```
Actually the google translation seems to be understandable enough: https://translate.google.fr/translate?sl=fr&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fwww.etalab.gouv.fr%2Fwp-content%2Fuploads%2F2017%2F04%2FETALAB-Licence-Ouverte-v2.0.pdf&edit-text=&act=url

**Comment by kbevers** [comment]
Yeah, I also tried running it through google translate and understood most of it. I missed the point about being compatible with CC-BY etc. Seems okay to me

@sebastic What's your take on this license ? Is it kosher in Debian?

**Comment by rouault** [comment]
The term "reuse" in the google translate traduction is an improper translation of "re-user", and would be better translated as the "licensee"

**Comment by rouault** [comment]
Perhaps @jdesboeufs who is working for Etalab (open data French portal) would be able to tell if there's an official English translation of the License Ouverte ?

**Comment by sebastic** [comment]
The use of non-standard open source licenses should be greatly discouraged, so I'm not happy that the French decided to invent their own license instead of using an existing well known license.

The license not having an official English translation is also a major downside. I'd be tempted to reject files under this license because of that.

The terms however seem to be compatible with the DFSG & OSD, but this cannot be judged fully because of machine translation.

Who should we contact to get an official English translation of this license? It would be great if they could provide the terms also in English like the Germans did in their license mentioned in #22.

**Comment by dgricci** [comment]
Here is the official [english translation of the french open license - OL/LO](https://www.etalab.gouv.fr/wp-content/uploads/2014/05/Open_Licence.pdf)

**Comment by rouault** [comment]
> Here is the official [english translation of the french open license - OL/LO](https://www.etalab.gouv.fr/wp-content/uploads/2014/05/Open_Licence.pdf)

Thanks  Didier !

**Comment by rouault** [comment]
I've updated the PR to add the link to English translation as well

**Comment by sebastic** [comment]
The terms of the official English translation seem to be compatible with the DFSG & OSD as well. I however still greatly discourage its use. I don't like the precent it sets in accepting non-standard licenses.

**Comment by kbevers** [comment]
@sebastic 	

> The terms of the official English translation seem to be compatible with the DFSG & OSD as well. I however still greatly discourage its use. I don't like the precent it sets in accepting non-standard licenses.

I agree that it would be better for organisations to use standard licenses but it is counter-productive to not include the grids when they are in fact released on a permissive license. Regarding setting a precedence, we have already allowed the [Canadian homemade license](http://open.canada.ca/en/open-government-licence-canada) into the repository so including this is not really doing anything new.

**Comment by mwtoews** [comment]
If it's important for upstream sources to consider their national copyright laws, I'd suggest they use a regional CC license instead, e.g. [CC BY 2.0 FR](https://creativecommons.org/licenses/by/2.0/fr/) or [CC BY 2.0 CA](https://creativecommons.org/licenses/by/2.0/ca/). (Just to be clear, it's up to the source providers to make that decision.)

**Comment by rouault** [comment]
Well, in an idea world every country could use English language in a official way and would not suffer from wheel-reinvention symptom, but that's for another battle I think. There have already been underground efforts to reach to the current result of having those data available under an open license (and which clearly states its intent to be compatible with other well-known similar licenses). We could still wait for many years to get to the "ideal" result.

**Pull request merged**
