### PR TITLE
Add exhaustive NAD83 -> NAD83(HPGN) shift grids

### PR DESCRIPTION
**Pull request by rouault**
The main proj-datumgrid package contains 5 grids (FL, MD, TN, WI, WO)
out of the full 51 grids for the 51 states. So we provide them in an
extensive way by using the build_nad83_harn.sh script that downloads
the source .los/.las files, and use the scripts/loslas2ntv2.py script
to convert them to NTv2.

Important note: https://download.osgeo.org/proj/hpgn_ntv2.zip contains
a similar content, except that this historical package had the sign of
the offsets reverse (so doing NAD83(HPGN) -> NAD83 conversion), because
of the requirements of the historical +nadgrids, that required grids to
go from a source CRS to WGS84 (here NAD83 was considered as being WGS84)
With the new +proj=hgridshift operator, we don't need such hacks, and
it is better to keep the grids as close as possible as their sources.

Discussion:
1) should we keep the 5 grids  (FL, MD, TN, WI, WO) that have equivalent content to flhpgn.gsb, mdhpgn.gsb, etc... ?
2) the size of the 51 grids is 1.5 MB. Should they be kept in north-america, or are they general purpose enough to be moved to main ?

### CODE REVIEW

**Comment by mwtoews** [comment]
I'd say the quantity and limited geographic extent of these files suggests they be kept in north-america

**Comment by mwtoews** [comment]
I wonder if a metadata table would help identify the filenames and regions. See (e.g.) [geographic_transformations.pdf](http://help.arcgis.com/en/arcgisdesktop/10.0/help/003r/pdf/geographic_transformations.pdf) for these relations, but perhaps a .csv file. For instance, it's not obvious that `c1hpgn.gsb` is for Saipan, near Guam, in the Pacific Ocean. And yeah, not all of these are in North America (i.e. not part of NAD).

**Comment by rouault** [comment]
> I wonder if a metadata table would help identify the filenames and regions

The metadata table will be the EPSG database (https://github.com/rouault/proj.4/blob/iso19111/data/sql/grid_transformation.sql) + the https://github.com/rouault/proj.4/blob/iso19111/data/sql/grid_alternatives.sql (to be completed to do the mapping between the .los/.las names and the .gsb ones) as part of my work of  https://github.com/rouault/proj.4/tree/iso19111

**Comment by kbevers** [comment]
Blah.. I was hoping to not have to make up my mind about this :-)

> should we keep the 5 grids (FL, MD, TN, WI, WO) that have equivalent content to flhpgn.gsb, mdhpgn.gsb, etc... ?

I guess these have been in circulation long enough that we better keep them around. At least for now.

> the size of the 51 grids is 1.5 MB. Should they be kept in north-america, or are they general purpose enough to be moved to main ?

Let's put them in north-america. I think we should try not put too much stuff into the main package.

**Review by kbevers — APPROVED** [review]

**Pull request merged**
