### PR TITLE
europe/NKG: add link to EUREF2019 Tutorial

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by rouault** [comment]
The build error has nothing to do with the commit

**Comment by kbevers** [comment]
As long as you are linking to the EUREF tutorial you may as well include the center of the tutorial :-)

https://github.com/kbevers/PROJTutorial

Also, please add this upstream instead: https://github.com/NordicGeodesy/NordicTransformations

**Comment by rouault** [comment]
Links to both github repo added

**Comment by kbevers** [comment]
Link to EUREF tutorial added upstream: https://github.com/NordicGeodesy/NordicTransformations/blob/master/resources/NKG

**Comment by rouault** [comment]
should I drop the [2] and [3] links, or will you add them upstream as well ?

**Comment by kbevers** [comment]
> should I drop the [2] and [3] links, or will you add them upstream as well ? 

Yes please. I was just joking about adding them, sorry if that wasn't clear.

**Comment by rouault** [comment]
ok, [2] and [3] removed

**Pull request merged**
