### PR TITLE
Add VERTCON .gtx grids (fixes https://github.com/OSGeo/proj.4/issues/1071)

### PR DESCRIPTION
**Pull request by rouault**
Those grids have been converted from the original NOAA grids with
the provided vertcon_94_to_gtx.py script.

Check
```
$ echo "-98.4803739 29.4667897 0" | ~/proj/proj.4//src/cct +proj=pipeline +step +proj=vgridshift +multiplier=0.001 +ellps=GRS80 +grids=./vertconc.gtx
-98.4803739000   29.4667897000        0.1288           inf
```

which is consistant with the EPSG database for epsg_coordoperationmethod = 9658 :
```
Then using bi-linear interpolation for 29.4667897°N, 98.4803739°W, offset = 0.129m
```

### CODE REVIEW

**Comment by sebastic** [comment]
The `vertcon_94_to_gtx.py` should probably be added to `CPACK_SOURCE_IGNORE_FILES` in `north-america/CMakeLists.txt` to not have it included in the archive, and hence not extracted to `$PROJ_DATA` when unpacking the archive.

**Comment by rouault** [comment]
> The vertcon_94_to_gtx.py should probably be added to CPACK_SOURCE_IGNORE_FILES

Good point. Commit amended

**Comment by sebastic** [comment]
I think this is good to merge now. Added @kbevers for a second opinion.

**Comment by kbevers** [comment]
Also looks good to me but since this PR was opened we decided to go a different way in PROJ as seen here: https://github.com/OSGeo/proj.4/pull/1072

So, with the addition of a grid value multiplier it is really not necessary to include the grids with updated units. I suggested adding them here before Even came up with the multiplier idea which I think is a better solution to this problem. 

The original grids with mm units can still be added here.

**Comment by rouault** [comment]
OK, I've reworked the script to let the values in millimeters

**Pull request merged**
